name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Init
        run: |
          df -h
          sudo apt-get update

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install requirements
        run: |
          df -h
          sudo apt-get update
          sudo apt-get install -y make

      - name: Build
        run: |
          df -h
          make build

      - name: Test
        run: |
          make Test
